"""initial tables

Revision ID: 3cf50545c487
Revises: 
Create Date: 2026-10-05 00:59:49.465434
"""
from alembic import op
import sqlalchemy as sa


revision = '3cf50545c487'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('locale', sa.String(length=35), nullable=False),
    sa.Column('email_consent', sa.Boolean(), nullable=False),
    sa.Column('opted_out', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('processed_webhooks',
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('cases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.Enum('checkout_decline', 'capture_denied', 'subscription_failed', 'capture_pending', 'checkout_abandoned', 'seeded', name='source', native_enum=False, length=32), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('paypal_order_id', sa.String(length=64), nullable=True),
    sa.Column('paypal_capture_id', sa.String(length=64), nullable=True),
    sa.Column('paypal_subscription_id', sa.String(length=64), nullable=True),
    sa.Column('paypal_invoice_id', sa.String(length=64), nullable=True),
    sa.Column('failure_code', sa.String(length=64), nullable=False),
    sa.Column('failure_category_hint', sa.Enum('soft', 'hard', 'pending', 'unknown', name='hint', native_enum=False, length=32), nullable=False),
    sa.Column('stage', sa.Enum('failed', 'diagnosed', 'proposed', 'checked', 'awaiting_approval', 'scheduled', 'sent', 'waiting', 'recovered', 'held', 'escalated', 'closed', name='stage', native_enum=False, length=32), nullable=False),
    sa.Column('frozen', sa.Boolean(), nullable=False),
    sa.Column('diagnosis', sa.JSON(), nullable=True),
    sa.Column('proposal', sa.JSON(), nullable=True),
    sa.Column('verdicts', sa.JSON(), nullable=True),
    sa.Column('message', sa.JSON(), nullable=True),
    sa.Column('recovered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_reason', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cases_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_cases_paypal_capture_id'), ['paypal_capture_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cases_paypal_invoice_id'), ['paypal_invoice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cases_paypal_order_id'), ['paypal_order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cases_stage'), ['stage'], unique=False)

    op.create_table('case_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('text', sa.String(length=500), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('case_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case_events_case_id'), ['case_id'], unique=False)

    op.create_table('touches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('touches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_touches_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_touches_customer_id'), ['customer_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('touches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_touches_customer_id'))
        batch_op.drop_index(batch_op.f('ix_touches_case_id'))

    op.drop_table('touches')
    with op.batch_alter_table('case_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case_events_case_id'))

    op.drop_table('case_events')
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cases_stage'))
        batch_op.drop_index(batch_op.f('ix_cases_paypal_order_id'))
        batch_op.drop_index(batch_op.f('ix_cases_paypal_invoice_id'))
        batch_op.drop_index(batch_op.f('ix_cases_paypal_capture_id'))
        batch_op.drop_index(batch_op.f('ix_cases_created_at'))

    op.drop_table('cases')
    op.drop_table('processed_webhooks')
    op.drop_table('customers')
    # ### end Alembic commands ###
